# perform checks on a file

# check the technical writing for various characteristics
- writing/outline.md:
    - description: Ensure that outline.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers in the outline.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the outline file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true

# check the technical writing for various characteristics
- writing/paper.md:
    - description: Ensure that paper.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers in the paper.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the paper file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
    - description: Delete the 'Add Your Account Name Here' prompt in the paper file
      check: MatchFileFragment
      options:
        fragment: "Add Your Account Name Here"
        count: 0
        exact: true
    - description: Write a minimum number of meaningful words (2000) in the paper
      check: CountFileWords
      options:
        count: 2000
        exact: false


# count number of commits in the GitHub repository
- description: Have at least a specific minimum number of commits (10) in repository
  check: CountCommits
  options:
    count: 10
